plugins {
    id 'net.fabricmc.fabric-loom'
    id 'com.matthewprenger.cursegradle' version '1.4.0'
    id 'com.modrinth.minotaur' version '2.+'
    id 'io.github.flemmli97.multiloader.platform-fabric'
    id 'io.github.flemmli97.multiloader.tiny-remapper'
}

remap {
    mappingVersion = "1.21.11"
}

repositories {
    mavenCentral()
    maven {
        name = 'Ladysnake Mods'
        url = 'https://maven.ladysnake.org/releases'
        content {
            includeGroup 'io.github.ladysnake'
            includeGroupByRegex 'io\\.github\\.onyxstudios.*'
        }
    }
    maven {
        url = "https://maven.jamieswhiteshirt.com/libs-release/"
        content {
            includeGroup 'com.jamieswhiteshirt'
        }
    }
    maven {
        url = "https://maven.nucleoid.xyz/"
        content {
            includeGroup 'eu.pb4'
        }
    }
}

dependencies {
    implementation include("io.github.flemmli97:lingua_bib:${lingua_bib}-fabric")
    implementation include('org.yaml:snakeyaml:2.4')

    implementation("me.lucko:fabric-permissions-api:${fabric_permissions_api}")

    yarnCompileOnly octo_economy_api
    yarnCompileOnly diamond_economy
    yarnCompileOnly "maven.modrinth:beconomy:${beconomy}"

    compileOnly "io.github.ladysnake:PlayerAbilityLib:${player_ability_lib}"

    //modRuntimeOnly "dev.ftb.mods:ftb-ranks-fabric:${ftb_ranks}"
    //modRuntimeOnly "dev.ftb.mods:ftb-chunks-fabric:${ftb_chunks}"
    compileOnly goml_reserved
    compileOnly "com.jamieswhiteshirt:rtree-3i-lite-fabric:0.3.0"

    yarnCompileOnly harvest_with_ease_fabric
    yarnCompileOnly "eu.pb4:common-protection-api:${common_prot_api}"
}

processResources {
    filesMatching(['fabric.mod_api.json']) {
        expand mod_meta
    }
}

tasks.register('apiJar', Jar) {
    dependsOn classes
    archiveClassifier.set "api-source"
    from sourceSets.main.output
    include "io/github/flemmli97/flan/api/**"
    include "fabric.mod_api.json" //Include this so it gets remapped as a dependency
    rename("fabric.mod_api.json", "fabric.mod.json")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact(apiJar) {
                builtBy apiJar
            }
        }
    }
}
