plugins {
    id 'fabric-loom' version '1.14-SNAPSHOT' apply false
    id 'net.neoforged.moddev' version '2.0.134' apply false
    id 'io.github.flemmli97.multiloader.discord_hook' version '1.+'
}

subprojects {
    repositories {
        mavenLocal()
        maven {
            name = "FTB"
            url = "https://maven.ftb.dev/releases"
            content {
                includeGroup 'dev.ftb.mods'
            }
        }
        maven {
            name = "Architectury"
            url = "https://maven.architectury.dev/"
            content {
                includeGroup 'dev.architectury'
            }
        }
        maven {
            name = "LinguaBib"
            url = "https://maven.blazing-coop.net/releases"
            content {
                includeGroup 'io.github.flemmli97'
            }
        }
        maven {
            name = "Modrinth"
            url = "https://api.modrinth.com/maven"
            content {
                includeGroup 'maven.modrinth'
            }
        }
        maven {
            name = "CurseMaven"
            url = "https://www.cursemaven.com"
            content {
                includeGroup 'curse.maven'
            }
        }
        maven {
            url = "https://maven.impactdev.net/repository/development/"
            content {
                includeGroupByRegex 'net.impactdev.*'
                includeGroup 'net.impactdev'
            }
        }
        maven {
            url = 'https://jitpack.io'
            content {
                includeGroupByRegex 'com.github.*'
            }
        }
    }
}