org.gradle.jvmargs=-Xmx4G
minecraft_version=1.21.1
neoForm_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.07.28
# NeoForge Properties
neo_loader_version=2
neoforge_version=21.1.4
# Fabric Properties
fabric_loader_version=0.15.11

# Mod Properties
mod_version=1.12.7
maven_group=io.github.flemmli97
mod_id=flan
mod_author=flemmli97

# Dependencies
fabric_version=0.116.4+1.21.1
fabric_permissions_api=0.3.1
dynmap_fabric=curse.maven:dynmap-59433:5442994
diamond_economy=curse.maven:diamondeconomy-534301:4574011
harvest_with_ease_fabric=curse.maven:harvestwithease-602171:4626583
octo_economy_api=com.github.ExcessiveAmountsOfZombies:OctoEconomyApi:5137175b1c
eights_economy=curse.maven:eightseconomy-559967:4593864
goml_reserved=curse.maven:goml-572651:5421480
minecolonies=1.20.1-1.1.8-ALPHA
common_prot_api=1.0.0
ftb_ranks=2100.1.0
ftb_chunks=2100.1.0
impactor_version=5.1.0
porting_lib=2.1.1192+1.20.1
create_fabric=0.5.1-f-build.1232+mc1.20.1
lingua_bib=1.21.1-1.0.6
dicemcmm=curse.maven:dicemc-money-mod-406972:5934828
player_ability_lib=1.10.0
beconomy=CpGrhJed

# Curse properties
curse_versions=1.21.1, Java 21
curse_page_fabric=https://www.curseforge.com/minecraft/mc-mods/flan
curse_id_fabric=404578
curse_dep_fabric=fabric-api
curse_page_forge=https://www.curseforge.com/minecraft/mc-mods/flan-forge
curse_id_forge=493246
curse_dep_forge=
modrinth_versions=1.21.1
modrinth_page=https://modrinth.com/mod/flan
modrinth_id=Si383TIH
modrinth_dep_fabric=fabric-api
modrinth_dep_forge=

# Other
project_name=Flan
full_changelog=https://github.com/Flemmli97/Flan/blob/1.21/Changelog.md
discord_role=852113509243682817
