plugins {
    id 'io.github.flemmli97.multiloader.platform-common'
    id 'io.github.flemmli97.multiloader.tiny-remapper'
}

remap {
    mappingVersion = "1.21.11"
}

repositories {
    maven {
        name = "Create Fabric"
        url = "https://mvn.devos.one/snapshots"
        content {
            includeGroupByRegex 'io.github.fabricators_of_create.*'
            includeGroup 'com.simibubi.create'
        }
    }
}

dependencies {
    jarJar(compileOnly('org.yaml:snakeyaml:2.4'))

    commonDependency dynmap_fabric

    commonDependency("dev.ftb.mods:ftb-ranks-neoforge:${ftb_ranks}")
    commonDependency("dev.ftb.mods:ftb-chunks-neoforge:${ftb_chunks}")

    commonDependency "com.github.BlueMap-Minecraft:BlueMapAPI:v2.2.1"
    commonDependency("net.impactdev.impactor.api:economy:${impactor_version}") {
        exclude group: "net.kyori"
    }

    commonDependency "info.journeymap:journeymap-api-common:${journeymap_api}"

    compileOnly("io.github.flemmli97:lingua_bib:${lingua_bib}-common")

    yarnCommonDependency("io.github.fabricators_of_create.Porting-Lib:entity:${porting_lib}")
    yarnCommonDependency("com.simibubi.create:create-fabric-1.20.1:${create_fabric}") {
        transitive = false
    }
}

sourceSets.main.resources {
    srcDir "src/generated/resources"
}

tasks.register('apiJar', Jar) {
    dependsOn classes
    archiveClassifier.set "common-api-source"
    from project(":common").sourceSets.main.output + sourceSets.main.output
    include "io/github/flemmli97/flan/api/**"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact(apiJar) {
                classifier "api"
                builtBy apiJar
            }
        }
    }
}