plugins {
    id 'io.github.flemmli97.multiloader.platform-common'
}

dependencies {
    jarJar(compileOnly('org.yaml:snakeyaml:2.4'))

    commonDependency dynmap_fabric

    commonDependency("dev.ftb.mods:ftb-ranks-neoforge:${ftb_ranks}")
    commonDependency("dev.ftb.mods:ftb-chunks-neoforge:${ftb_chunks}")

    commonDependency "com.github.BlueMap-Minecraft:BlueMapAPI:v2.2.1"
    commonDependency("net.impactdev.impactor.api:economy:${impactor_version}") {
        exclude group: "net.kyori"
    }

    commonDependency "info.journeymap:journeymap-api-common:${journeymap_api}"

    compileOnly("io.github.flemmli97:lingua_bib:${lingua_bib}-common")
}

sourceSets.main.resources {
    srcDir "src/generated/resources"
}

tasks.register('apiJar', Jar) {
    dependsOn classes
    archiveClassifier.set "common-api-source"
    from project(":common").sourceSets.main.output + sourceSets.main.output
    include "io/github/flemmli97/flan/api/**"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact(apiJar) {
                classifier "api"
                builtBy apiJar
            }
        }
    }
}