plugins {
    id 'io.github.flemmli97.multiloader.platform-neoforge'
}

neoForge {
    runs {
        var common = project(":common")
        data {
            data()
            programArguments.addAll "--all", "--mod", "flan"
            programArguments.addAll "--output", common.file("src/generated/resources").absolutePath
        }
        client {
            jvmArgument "-XX:+AllowEnhancedClassRedefinition"
        }
    }
}

repositories {
    maven {
        name = "minecolonies"
        url = "https://ldtteam.jfrog.io/ldtteam/modding/"
    }
}

dependencies {
    jarJar(implementation("io.github.flemmli97:lingua_bib:${lingua_bib}-neoforge"))
    jarJar(implementation('org.yaml:snakeyaml:2.4'))

    compileOnly dicemcmm

    //runtimeOnly "dev.ftb.mods:ftb-ranks-neoforge:${ftb_ranks}"
    //runtimeOnly "dev.ftb.mods:ftb-chunks-neoforge:${ftb_chunks}"

    //CompileOnly cause dependencies
    compileOnly "com.ldtteam:minecolonies:${minecolonies}"
}

tasks.register('apiJar', Jar) {
    dependsOn classes
    archiveClassifier.set "api"
    from sourceSets.main.output
    include "io/github/flemmli97/flan/api/**"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact(apiJar) {
                builtBy apiJar
            }
        }
    }
}
