name: Sync Labels
on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: Label Sync
        uses: EndBug/label-sync@v2.3.3
        with:
          token: ${{ github.token }}
          config-file: 'https://gist.githubusercontent.com/Flemmli97/737956ff9653e1f2416bb7c7a9050514/raw/common_mod_labels.yml'
          delete-other-labels: true